server:
  port: 8080
spring:
  datasource:
      name: springbootdb
      url: jdbc:mysql://127.0.0.1:3306/library?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      ## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
#mybatis:
#  mapper-locations: cn.mikey.eas.Mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: cn.mikey.eas.Pojo # 注意：对应实体类的路径
#  configuration:
##  驼峰法命名
#    map-underscore-to-camel-case: false
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  打印日志
logging:
  level:
    #Mapper所在的包
    com.mikey.eas.Mapper: debug